name: "Mauricio Rivera"
description: "Some interesting stuff"
title: "This page is Mauricio's Page"

url: "[YOUR DOMAIN]"

paginate: 5
paginate_path: /blog/page:num


markdown: maruku
permalink: pretty

authors:
  maurrivera:
    name: Mauricio Rivera	
    display_name: Mauricio Rivera
    gravatar: 
    email: maurrivera@gmail.com
    web: 
    twitter: maurrivera	
    github: maurlamf
